name: Continuous Integration

on: [push, pull_request]

jobs:
  setup-and-test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php-version: ['8.0.9'] # Define other PHP versions here if needed

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libxml2-dev
        # Add other dependencies here

    - name: Start PostgreSQL service
      run: |
        sudo service postgresql start

  deploy-to-dev:
    runs-on: ubuntu-20.04
    needs: setup-and-test
    if: contains(github.ref, 'refs/heads/dev')
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Development
      run: |
        echo "Deploying to development server..."
        # Your deployment script for dev

  deploy-to-staging:
    runs-on: ubuntu-20.04
    needs: setup-and-test
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Staging
      run: |
        echo "Deploying to staging server..."
        # Your deployment script for staging

  deploy-to-production:
    runs-on: ubuntu-20.04
    needs: setup-and-test
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Production
      run: |
        echo "Deploying to production server..."
        # Your deployment script for production

  notify-slack:
    runs-on: ubuntu-20.04
    if: always() # This ensures notification even if the previous steps failed
    steps:
    - name: Notify Slack
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: your-slack-channel
        SLACK_COLOR: '#ff0000' # Change color based on success or failure
        SLACK_MESSAGE: 'Deployment to production completed!'
        SLACK_TITLE: 'Deployment Status'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }} # Set this in your repo secrets
