name: CI

on:
  push:
    branches: 
      - '**'
    tags-ignore:
      - '**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      TEST_SUITE: ${{ matrix.test_suite }}
    strategy:
      matrix:
        test_suite: ['default', 'javascript']
        include:
          - test_suite: 'default'
            php_version: '7.4'
          - test_suite: 'javascript'
            node_version: '14'

    steps:
    - uses: actions/checkout@v2

    - name: Set up PHP and PostgreSQL
      if: matrix.test_suite != 'javascript'
      run: |
        sudo add-apt-repository -y ppa:ondrej/php
        sudo apt-get update
        sudo apt-get --yes remove postgresql\*
        sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
        wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
        sudo apt -y update
        sudo apt-get install -y postgresql-14 postgresql-client-14 libxml2-dev
        # Configure PostgreSQL as needed here...

    - name: Set up Node.js
      if: matrix.test_suite == 'javascript'
      uses: actions/setup-node@v2
      with:
        node-version: '${{ matrix.node_version }}'
    
    # Add additional steps for your build and test process here
    # ...

  deploy:
    needs: build
    runs-on: ubuntu-20.04
    if: ${{ github.ref != 'refs/heads/master' && startsWith(github.ref, 'refs/heads/dev@') }}
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Dev Server
      run: |
        # Your deployment script for dev server
        echo "Deploying to dev server..."

    # Define similar steps for staging and production environments
    # ...
